typo combing
DarkFlippers/unleashed-firmware pull request #352
Opened 2023-02-20 04:08 UTC by Round-Pi

# What's new

- [ Describe changes here ]

# Verification 
- Build fbt
- Update firmware on Flipper Zero and see if anything breaks

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2023-02-20 08:48 UTC, xMasterX requested changes
Hi, amiibo was named ameebo to avoid nintendo copyrights issues
Do not rename that

Second thing, you changed submodules
lib/FreeRTOS-Kernel
lib/STM32CubeWB
We can't accept such changes

also revert changes to debug/fw.jflash

2023-02-20 14:33 UTC, Round-Pi commented
Alright, I made the changes.

2023-02-20 15:29 UTC, xMasterX requested changes

2023-02-20 15:29 UTC, xMasterX commented on firmware/targets/f7/ble_glue/app_conf.h
> -#define CFG_OTP_END_ADRESS OTP_AREA_END_ADDR
This needs to be reverted

also Ameebo needs to be reverted

2023-02-20 15:57 UTC, Round-Pi commented
Done. Are there any other changes I should fix?

2023-02-20 16:06 UTC, xMasterX commented
> Done. Are there any other changes I should fix?

thanks, other things looks ok, i will test that nothing is broken today/tomorrow and will merge it

2023-02-21 16:27 UTC, Round-Pi commented
If it doesn't work, I can revert all the typo-fixes, except for the ones in comments and documents.

2023-02-21 20:56 UTC, xMasterX approved these changes
Thanks!

2023-02-21 20:56 UTC, merged